### ISSUE TITLE
CUBaseMiniDiagnosticsView doesn't update unless redrawn by usercontrol parent [BUG] [FEATURE]

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/tcopen-app-templates#100]
**Describe the bug**
CUBaseMiniDiagnosticsView is only shown when UI elements are redrawn. ie exiting then reentering the view otherwise it remains static showing outdated data or not showing relevant data. 

**To Reproduce**
1. Go to any cu that will produce diagnostic messages in its context.
2. Wait for messages to show up.
3. After messages fail to appear exit to operator view and reenter cu view.
4. Diagnostic messages appear, but do not dissapear or change.

**Expected behavior**
Messages sould appear and dissappear as they do in the model or at least poll changes at set intervals if it would be too much of a performance hit or would cause issues viewing the results.

**Screenshots**
<img width="962" alt="image" src="https://github.com/TcOpenGroup/tcopen-app-templates/assets/6548027/381df4ea-443a-4cdb-b49a-7bb37a1ca475">

**Additional remark**
It would be neat if the number of messages could be limited to only a handful.

**Comment by peterbarancek** [comment]
cleses #131
