### ISSUE TITLE
[BUG] Clean cycle times show sequence cycle times

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/tcopen-app-templates#102]
**Describe the bug**
Clean cycle time should show the elapsed time from calling StartCleanCycleTime() instead it shows SequenceElapesedTime.

CuBase.UpdateInfo() :
![image](https://github.com/TcOpenGroup/tcopen-app-templates/assets/6548027/3ab8ed3f-9826-4622-9b02-5a6fa8e42ca4)

That GroundTask should be AutomatTask, this will fix what is displayed. Though a better solution would be:

![image](https://github.com/TcOpenGroup/tcopen-app-templates/assets/6548027/3e5cd44e-48b4-44de-8cc7-240d3464e052)

Furthermore, _startCleanCycleTime and _stopCleanCycleTime should be reset when ground is called and when the Automat sequence finishes or when it starts each iteration. OnStart did not work for me so please advise. Thanks

**Comment by KrisztianOlah** [comment]
After a second look; Resetting _startCleanCycleTime and _stopCleanCycleTime in TcoTaskSequencer.CompleteSequence() will reset each iteration.

**Comment by peterbarancek** [comment]
closes #112

**Comment by peterbarancek** [comment]
closes #112
