### ISSUE TITLE
[BUG] Average cycle time shows incorrect value

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/tcopen-app-templates#103]
**Describe the bug**
Average cycle time shows about tenth of the correct value. 

The problem is in TcoTaskedSequencer. StopCleanCycleTime() :

<img width="935" alt="image" src="https://github.com/TcOpenGroup/tcopen-app-templates/assets/6548027/f5caa4cd-d7b3-4b63-8224-866e2b512ccc">

On the first cycle StopCleanCycleTime is called _LastCycleTime is T#0MS as it will only be written to by CompleteSequence which is generally called after StopCleanCycleTime. Also for the same reason there is no point calculating _cycleTimeAnalitics.Average, but we need _cycleTimeAnalitics.AverageCleanCycle.

**Comment by peterbarancek** [comment]
closes #112
