### ISSUE TITLE
[BUG] Users are able to enter manual mode without adequate permissions, potentially leading to unauthorized actions

### ISSUE THREAD

**Issue by mhareznik** [TcOpenGroup/tcopen-app-templates#120]
Despite lacking the necessary permissions, users can access the manual mode feature within the TcOpen framework. This presents a safety vulnerability as it allows unauthorized individuals to manipulate the component movements and potentially causing crashes. Urgent action is required to rectify this issue and ensure that only authorized users can utilize manual mode within the TcOpen framework.

**Comment by PTKu** [comment]
@peterbarancek This is probably in application template.
