### ISSUE TITLE
[ENHANCEMENT] Online Technological Settings in Controlled Unit

### ISSUE THREAD

**Issue by mhareznik** [TcOpenGroup/tcopen-app-templates#134]
Currently, when accessing the Controlled Unit from the Main View, users lack the ability to review the station's current Technological Settings. This functionality could prove beneficial in certain situations. Therefore, it's proposed to introduce a feature that mirrors the accessibility of Online Data, enabling users to seamlessly open and inspect the actual technological settings of the station.

**Comment by peterbarancek** [comment]
closes #132

**Comment by peterbarancek** [comment]
closes #131
