### ISSUE TITLE
[ENHANCEMENT] Custom Data Selector

### ISSUE THREAD

**Issue by mhareznik** [TcOpenGroup/tcopen-app-templates#135]
In OperatorView, TcoDataExchangeSimpleSelectorView from the TcOpen.Inxton.Data.Wpf library is actually used. The problem is that longer names of Process Settings, such as those with 14 characters, are not displayed correctly. A nice-to-have feature would be the ability to edit the view directly in the app template with filter option.

**Comment by peterbarancek** [comment]
It has been done in TcOpen repository. Layout was fixed in https://github.com/TcOpenGroup/TcOpen/releases/tag/0.11.0-alpha.71
