### ISSUE TITLE
Create template for Blazor TcOpen application

### ISSUE THREAD

**Issue by PTKu** [TcOpenGroup/tcopen-app-templates#48]
Create application template along the mts-s-template for Blazor platform. Take inspiration from 
https://github.com/TcOpenGroup/tcopen-app-templates/tree/dev/templates/mts-s-template/t

- [x] Add dataviews to the template
- [ ] Try to understand and implement MVVM using VMs from WPF application where possible. (@TimothyBucka)
- [ ] Add controlled unit views to the template

**Comment by peterbarancek** [comment]
\cib

**Comment by PTKu** [comment]
-[ ] Add dataviews to the template
