### ISSUE TITLE
PlcConnector ApplicationSettings typo + static request[BUG]

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/tcopen-app-templates#95]
**Describe the bug**
There is a typo in templates/mts-s-template/t/src/x_template_xPlcConnector/ApplicationSettings.cs on line 8.

public static DeployMode DeployMode{ get; set; } = DeployMode.Local;

DepoyMode should be DeployMode.

Furthermore can we make this a static field which would allow for easier access to this property.

I'm using it for the following now, but sometimes in other contexts such as auto logon or adding controls that are not supposed to be in the release environment:
 
`if (Debugger.IsAttached /*|| ApplicationSettings.DeployMode == DeployMode.Local*/ || ApplicationSettings.DeployMode == DeployMode.Dummy)
            {
                this.WindowStyle = WindowStyle.SingleBorderWindow; ;
            }
            else this.WindowStyle = WindowStyle.None;`

Thanks.

**Comment by peterbarancek** [comment]
closes #99
