### ISSUE TITLE
Lanaguage selector not changing the language of mts-s template app [BUG]

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/tcopen-app-templates#96]
**Describe the bug**
Language selector is not working.

**To Reproduce**
1. Ensure that tarnslations are available for the target languages.
2. Click on language selector.
3. Select any language that differs from the default.
4. Application restarts with the default language.

**Expected behavior**
Application sets new language and then restarts using said language strings.

**Screenshots**
<img width="870" alt="image" src="https://github.com/TcOpenGroup/tcopen-app-templates/assets/6548027/d6430925-1a53-4e53-b475-996b757a6f63">

The above code has no logic for setting any other language than the default.

**Comment by KrisztianOlah** [comment]
Bug can be solved by setting Setting.Settings to public in xTemplatexHmi.WPF, removing Setting.Settings from xTemplatexOP and prepending Settings with xTemplatexHmi.WPF.Properties or adding a matching using statement in App.xaml.cs (xTemplatexOP).

**Comment by peterbarancek** [comment]
closes #99
