### ISSUE TITLE
Language selector cancel function [ENHANCEMENT]

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/tcopen-app-templates#97]
**Is your feature request related to a problem? Please describe.**
Clicking on language selector cannot be cancelled by user, user must set a language in order to exit the dialog. 

**Describe the solution you'd like**
Either a cancel on lost focus or a cancel button would suffice.

**Comment by peterbarancek** [comment]
closes #99

**Comment by peterbarancek** [comment]
closes #99
