### ISSUE TITLE
MTS-S template: Application bar Expander in Mainview.xaml does not collapse[BUG]

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/tcopen-app-templates#98]
closes #99 
**Describe the bug**
Pressing the collapse button changes the button state, but not the content state to collapsed.

**To Reproduce**
1. Go to main view screen.
2. Click on the collapse button in the bottom rigth corner.
4. See no effect on the content on the small arrow.

**Expected behavior**
It's expected that the bar collapses to its minimum size and does not display its contents.

**Screenshots**
<img width="885" alt="image" src="https://github.com/TcOpenGroup/tcopen-app-templates/assets/6548027/0cfa7b31-ba96-47fe-8a88-32b04f8820fe">

**Comment by peterbarancek** [comment]
closes #99

**Comment by peterbarancek** [comment]
closes #99
